import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,Check,ChevronDown,ChevronRight,ShieldCheck,LockKeyhole,Globe,MoreHorizontal,Plus,RotateCcw,X,FileText,Table2,PenLine,Sparkles,Activity as ActivityIcon,Download,CheckCircle2,Loader2,TriangleAlert,GraduationCap,MapPin,Clock,ExternalLink,SlidersHorizontal,Command,Eye,Layers,Zap,Send,Shield,Pause} from 'lucide-react';
import type {Activity,Flow,Phase,Profile,Receipt,Snapshot} from './types';
import {sampleProfile} from './types';
import {firewall,protect} from './privacy';
import {demoSnapshot,extensionMessage} from './demo';

const isExtension=location.pathname.endsWith('sidepanel.html')&&location.protocol==='chrome-extension:';
const phaseLabels:Record<Phase,string>={idle:'Ready when you are',planning:'Making a plan',observing:'Reading the page',perceiving:'Finding the right context',protecting:'Protecting your information',transmitting:'Preparing safe context',reasoning:'Connecting the dots',validating:'Checking every action',approval:'Your approval is needed',executing:'Putting your plan in motion',verifying:'Checking the result',replanning:'Adapting to the page',complete:'All set. You’re in control.',error:'Let’s take a different path',cancelled:'Paused at your request'};
const flowCopy:Record<Flow,{title:string;goal:string;icon:typeof FileText}>={application:{title:'Apply to a fellowship',goal:'Help me apply to the Meridian Research Fellowship.',icon:GraduationCap},summary:{title:'Summarize page',goal:'Summarize this page and highlight what matters.',icon:FileText},form:{title:'Fill a form',goal:'Fill the application using my local profile.',icon:PenLine},extract:{title:'Extract data',goal:'Extract the key details from this page.',icon:Table2},'privacy-scan':{title:'Privacy scan',goal:'Scan the active page for privacy risks and sensitive data exposure.',icon:ShieldCheck}};
const stages=['Observe','Perceive','Protect','Reason','Validate','Act','Verify'];
function Logo({small=false}:{small?:boolean}){return <span className={'brand '+(small?'small':'')}><img src="./favicon.svg" alt=""/><span>orvia<span className="brand-dot">.</span></span></span>}
function saveFile(name:string,value:string,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function mergeFindings(items:Receipt['findings']){return items.reduce<Receipt['findings']>((out,item)=>{const prior=out.find(i=>i.kind===item.kind);if(prior)prior.count+=item.count;else out.push({...item});return out;},[]);}

export default function App(){
 const [phase,setPhase]=useState<Phase>('idle');const [flow,setFlow]=useState<Flow>('application');const [goal,setGoal]=useState('');const [logs,setLogs]=useState<Activity[]>([]);const [receipt,setReceipt]=useState<Receipt|null>(null);const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [drawer,setDrawer]=useState<'activity'|'privacy'|'metrics'|'profile'|null>(null);const [profile,setProfile]=useState<Profile>({...sampleProfile});const [page,setPage]=useState<'overview'|'application'>('overview');const [filled,setFilled]=useState(false);const [submitted,setSubmitted]=useState(false);const [result,setResult]=useState('');const [error,setError]=useState('');const [progress,setProgress]=useState(0);const [pending,setPending]=useState<{id:string;origin:string;fields:string[]}|null>(null);const [chaos,setChaos]=useState(false);const [fallback,setFallback]=useState(false);const [elapsed,setElapsed]=useState(0);const [launched,setLaunched]=useState(false);
 const runId=useRef(0);const started=useRef(0);const input=useRef<HTMLTextAreaElement>(null);const dialog=useRef<HTMLDivElement>(null);const active=!( ['idle','complete','error','cancelled'] as Phase[]).includes(phase);
 useEffect(()=>{if(!drawer)return;const prior=document.activeElement as HTMLElement|null;dialog.current?.focus();function key(e:KeyboardEvent){if(e.key==='Escape')setDrawer(null);if(e.key==='Tab'){const nodes=dialog.current?.querySelectorAll<HTMLElement>('button,input,textarea,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus();};},[drawer]);
 useEffect(()=>()=>{runId.current++;},[]);
 useEffect(()=>{if(!active)return;const timer=setInterval(()=>setElapsed((performance.now()-started.current)/1000),100);return()=>clearInterval(timer);},[active]);
 function log(stage:string,detail:string,boundary:Activity['boundary']='Browser'){setLogs(l=>[...l,{stage,detail,boundary,time:new Date().toLocaleTimeString('en-GB')}]);}
 async function step(id:number,next:Phase,pct:number,stage:string,detail:string,boundary:Activity['boundary']='Browser'){if(id!==runId.current)throw new Error('cancelled');setPhase(next);setProgress(pct);log(stage,detail,boundary);await new Promise(r=>setTimeout(r,650));if(id!==runId.current)throw new Error('cancelled');}
 function cancel(){runId.current++;setPhase('cancelled');setPending(null);log('Pause','Run cancelled. No further actions will be requested.');if(isExtension)void extensionMessage('CANCEL');}
 function reset(){runId.current++;setPhase('idle');setProgress(0);setLogs([]);setReceipt(null);setSnapshot(null);setResult('');setError('');setPending(null);setFilled(false);setSubmitted(false);setPage('overview');setGoal('');setElapsed(0);if(isExtension)void extensionMessage('CANCEL');}
 function finish(text:string){const duration=(performance.now()-started.current)/1000;setResult(text);setProgress(100);setElapsed(duration);setReceipt(r=>r?{...r,elapsed:duration}:r);setPhase('complete');log('Complete','Result delivered. Session context remains in memory.');}
 async function start(selected:Flow=flow){
  if(active)return;const id=++runId.current;started.current=performance.now();setLaunched(true);setFlow(selected);setFilled(false);setSubmitted(false);setLogs([]);setReceipt(null);setError('');setResult('');setPending(null);setElapsed(0);
  try{
   await step(id,'planning',6,'Plan',`Selected capability: ${flowCopy[selected].title}. Fixed local prototype planner.`,'Local planner');
   await step(id,'observing',17,'Observe',isExtension?'Reading visible DOM text and empty field metadata in the active tab.':'Reading the Meridian fixture. This is a simulated browser page.');
   const snap=isExtension?await extensionMessage<Snapshot>('OBSERVE'):demoSnapshot();if(id!==runId.current)return;setSnapshot(snap);
   await step(id,'perceiving',29,'Perceive','DOM → semantic labels → focused regions. OCR/vision escalation is simulated; no screenshot captured.');
   if(fallback)await step(id,'replanning',32,'Fallback','Visual perception unavailable (demo). Continuing with DOM text and accessible labels.');
   await step(id,'protecting',42,'Protect',`${snap.findings.reduce((n,f)=>n+f.count,0)} text patterns masked; ${snap.blocked} sensitive fields excluded. Rule-based detection, not exhaustive.`);
   const sanitized=protect(JSON.stringify({goal:goal||flowCopy[selected].goal,title:snap.title,text:snap.text,fields:snap.fields.map(f=>({label:f.label,key:f.key,type:f.type}))}),profile);
   const payload=firewall(sanitized.text);
   const newReceipt:Receipt={id:crypto.randomUUID(),time:new Date().toISOString(),findings:mergeFindings([...snap.findings,...sanitized.findings]),blocked:snap.blocked,payload,bytes:new TextEncoder().encode(payload).length,networkBytes:0,status:'local-only',elapsed:0};setReceipt(newReceipt);
   await step(id,'transmitting',52,'Egress firewall','Sanitized payload accepted by local mock boundary. External transmission disabled: 0 bytes.','Policy');
   await step(id,'reasoning',63,'Reason','Local deterministic planner consumes sanitized context. Page text is treated as untrusted data.','Local planner');
   await step(id,'validating',74,'Validate',selected==='summary'||selected==='extract'?'Read-only result; no DOM mutation is required.':'Only recognized empty text fields may be filled. Passwords, payments and submission are blocked.','Policy');
   if(selected==='summary'){
    await step(id,'verifying',93,'Verify','Checking the summary against the observed text.');finish(isExtension?snap.text.split('\n').filter(t=>t.length>35).slice(0,5).join('\n\n')||snap.text:'A paid, 12-week research fellowship at Meridian for undergraduates working at the intersection of responsible AI and human–computer interaction.\n\n₹25,000 / month · Bengaluru, hybrid\nApply by 30 November 2026.\n\nPrepare your academic details and a portfolio. Selection includes an application review and two conversations.');return;
   }
   if(selected==='extract'){await step(id,'verifying',93,'Verify','Structured fields derived from the sanitized observation.');finish('Key page details are ready. Export a JSON copy below.');return;}
   if(chaos){await step(id,'replanning',77,'Replan','Demo page layout changed. Discarding stale handles and observing again.');if(isExtension)await extensionMessage('OBSERVE');log('Observe','Fresh field map acquired. A new approval will cover the current plan.');}
   const approval=isExtension?await extensionMessage<{id:string;origin:string;fields:string[]}>('PREPARE',{profile}):{id:crypto.randomUUID(),origin:'https://meridian.example',fields:Object.keys(profile).filter(k=>profile[k as keyof Profile])};
   if(id!==runId.current)return;if(!approval.fields.length)throw new Error('Add values to your local profile before filling.');setPending(approval);setPage('application');setPhase('approval');setProgress(80);log('Approval','Waiting for review of the destination and exact local profile values.','Policy');
  }catch(e){if(id!==runId.current)return;setError(e instanceof Error?e.message:'Something went wrong.');setPhase('error');log('Blocked',e instanceof Error?e.message:'Action failed.','Policy');}
 }
 async function approve(){if(!pending||phase!=='approval')return;const id=runId.current;const current=pending;setPending(null);try{
  await step(id,'executing',86,'Act',isExtension?'Applying approved values to the same tab and document.':'Filling the sample application. Submission is simulated.');
  if(isExtension)await extensionMessage('EXECUTE',{id:current.id});if(id!==runId.current)return;setFilled(true);
  await step(id,'verifying',96,'Verify',isExtension?'Content script read-back confirmed the values were retained.':'Fixture state confirms the expected fields. No real application was submitted.');
  if(!isExtension&&flow==='application')setSubmitted(true);
  finish(isExtension?'Supported fields filled and verified. Review the website, then submit manually when you’re ready.':flow==='application'?'Application prepared and demo submission verified. Your sample application is ready for its next chapter.':'Your sample details are filled in. Review them on the page before continuing.');
 }catch(e){if(id!==runId.current)return;setError(e instanceof Error?e.message:'Action failed.');setPhase('error');log('Verify failed','Stopped safely. Re-observe the page and approve a fresh plan.','Policy');}}
 const data=snapshot?{title:snapshot.title,origin:snapshot.origin,headings:snapshot.headings,excerpt:snapshot.text,...(!isExtension?{stipend:'INR 25,000/month',duration:'12 weeks',location:'Bengaluru / Hybrid',deadline:'2026-11-30'}:{})}:{};
 return <div className={isExtension?'extension-root':'app'}>
 {!isExtension&&<><header className="topbar"><Logo/><div className="top-nav"><span className="nav-active">Interactive demo</span><button onClick={()=>setDrawer('activity')}>How it works <ArrowUpRight size={13}/></button></div><div className="top-right"><span className="prototype-tag">PRODUCT PROTOTYPE</span><a className="github-link" href="./orvia-extension.zip" download>Get extension <Download size={14}/></a></div></header><section className="intro"><div><div className="eyebrow"><span/> A LITTLE LESS BUSYWORK. A LOT MORE POSSIBILITY.</div><h1>Your intent. <span>In motion.</span></h1><p>A browser agent that gets things done. Your private data stays with you.</p></div><button className="launch-button" onClick={()=>{setLaunched(true);input.current?.focus();document.getElementById('workspace')?.scrollIntoView({behavior:'smooth',block:'start'});}}>{launched?'Explore the workspace':'Launch Interactive Demo'}<ArrowUpRight size={17}/></button></section>
 <div className="workspace-top"><div className="demo-label"><span className="live-dot"/> LIVE PLAYGROUND <span className="line-divider"/> Sample environment · no real applications</div><button className="text-button" onClick={reset}><RotateCcw size={13}/> Reset demo</button></div></>}
 <main className="workspace" id="workspace">
 {!isExtension&&<section className="browser" aria-label="Demo browser"><div className="browser-chrome"><div className="traffic"><i/><i/><i/></div><div className="browser-tab"><span className="meridian-icon">m</span> Meridian · Research Fellowship <X size={11}/></div><Plus size={14}/><div className="chrome-right"><MoreHorizontal size={17}/></div></div><div className="address-bar"><ArrowLeft size={15}/><ArrowRight size={15}/><RotateCcw size={14}/><div className="url"><LockKeyhole size={11}/><span>meridian.example <span className="url-path">/ careers / research-fellowship</span></span><ShieldCheck size={13}/></div><span className="tiny-logo">o</span></div>
 <div className={'site-surface '+(phase==='observing'||phase==='perceiving'?'observing':'')}><nav className="meridian-nav"><a href="#workspace" className="meridian-brand"><span className="meridian-icon">m</span> meridian<span>®</span></a><span>Research</span><span>Our people</span><span className="careers">Careers <span>04</span></span><Globe size={17}/></nav>
 <div className="opportunity-content"><div className="breadcrumb">Careers <ChevronRight size={12}/> Early careers <ChevronRight size={12}/> Research fellowship</div><div className="opportunity-hero"><div className="opportunity-copy"><span className="pill open"><span/> APPLICATIONS OPEN</span><h2>Curiosity meets<br/>real-world impact.</h2><p>Meridian Research Fellowship</p><div className="opportunity-tags"><span><MapPin size={13}/> Bengaluru · Hybrid</span><span><Clock size={13}/> 12 weeks</span></div></div><div className="orb-art" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="orbit three"/><div className="orb-core"/><span className="star a">✦</span><span className="star b">+</span><span className="art-caption">IDEAS WITHOUT LIMITS</span></div></div>
 <div className="site-tabs"><button onClick={()=>setPage('overview')} className={page==='overview'?'selected':''}>Overview</button><button onClick={()=>setPage('application')} className={page==='application'?'selected':''}>Your application {filled&&<Check size={12}/>}</button><span>Closes 30 Nov 2026</span></div>
 {page==='overview'?<div className="overview-grid"><article><h3>Build what comes next.</h3><p>Work alongside researchers, designers and engineers turning ambitious ideas into meaningful change.</p><h4>A space for curious minds</h4><p>Explore responsible AI, human–computer interaction and tools that help people do more. Bring your perspective. We’ll help you take it further.</p><div className="eligibility"><GraduationCap size={20}/><div><strong>Made for emerging talent</strong><p>Undergraduate students in computer science, design or related disciplines.</p></div></div><small className="sample-contact">Questions? fellowships@example.com · +91 80000 00000</small></article><aside className="role-card"><span className="eyebrow">THE OPPORTUNITY</span><h3>Research Fellow</h3><div className="stipend">₹25,000 <span>/ month</span></div><p>Paid internship · 2026 cohort</p><div className="role-line"/><span><Check size={13}/> Work with a dedicated mentor</span><span><Check size={13}/> Solve meaningful problems</span><button onClick={()=>{setPage('application');setFlow('application');setGoal(flowCopy.application.goal);input.current?.focus();}}>Start your application <ArrowUpRight size={14}/></button><small>It starts with a little curiosity.</small></aside></div>:<div className="application-area">{submitted?<div className="submission"><span className="success-orb"><Check size={26}/></span><span className="eyebrow">DEMO CONFIRMATION</span><h3>Great things start here.</h3><p>Your sample application is complete.</p><span className="reference">MER–DEMO–2026 · No real submission</span><button className="text-button" onClick={()=>setSubmitted(false)}>Review application <ArrowRight size={13}/></button></div>:<><div className="form-title"><div><h3>Your next chapter.</h3><p>A few details to get to know you.</p></div><span className="pill">SAMPLE FORM</span></div><div className="sample-form">{Object.entries(profile).map(([key,value])=><label key={key}>{({name:'Full name',email:'Email address',phone:'Phone number',university:'University'} as Record<string,string>)[key]}<input readOnly value={filled?value:''} placeholder={key==='email'?'you@example.com':key==='name'?'Your full name':key==='phone'?'+91 Your phone number':'Your institution'} className={filled?'filled':''}/>{filled&&<Check size={13}/>}</label>)}</div><div className="blocked-field"><LockKeyhole size={14}/><span>Account password</span><span>••••••••</span><span className="blocked-tag">Excluded by ORVIA</span></div><p className="form-note"><ShieldCheck size={13}/> Demo values only. Use ORVIA to prepare this application.</p></>}</div>}
 <footer className="meridian-footer"><span>© 2026 Meridian. Fictional demo organization.</span><span>Made for what’s next. ↗</span></footer></div>{phase==='observing'&&<div className="scan-line"/>}</div></section>}
 <aside className="agent-panel" aria-label="ORVIA agent"><div className="panel-header"><Logo small/><div className="panel-header-actions"><span className="pill beta">PREVIEW</span><button className="icon-button" aria-label="New task" disabled={active} onClick={reset}><Plus size={18}/></button><button className="icon-button" aria-label="Local profile and settings" disabled={active} onClick={()=>setDrawer('profile')}><SlidersHorizontal size={17}/></button></div></div><button className="privacy-banner" onClick={()=>setDrawer('privacy')}><ShieldCheck size={15}/><span>Private by design</span><span className="local-dot"/> Local-only <ChevronRight size={13}/></button>
 <div className="panel-body"><div className="context-chip"><Globe size={13}/><span>{isExtension?(snapshot?.origin||'Your active tab'):'meridian.example'}</span><span className="context-indicator"/></div>
 {phase==='idle'?<><div className="welcome"><div className="assistant-glyph"><Sparkles size={25}/></div><h2>A little help.<br/>A lot of possibility.</h2><p>Tell me what you’d like to do.<br/>I’ll take care of the steps.</p></div><div className="suggestions">{(['summary','form','extract'] as Flow[]).map(f=>{const Icon=flowCopy[f].icon;return <button key={f} onClick={()=>{setFlow(f);setGoal(flowCopy[f].goal);void start(f);}}><span className={'suggestion-icon '+f}><Icon size={16}/></span><span>{flowCopy[f].title}</span><ArrowUpRight size={14}/></button>;})}</div><button className="featured-flow" onClick={()=>{setFlow('application');setGoal(flowCopy.application.goal);void start('application');}}><span className="featured-top"><span><Sparkles size={12}/> TRY A COMPLETE WORKFLOW</span><ArrowUpRight size={14}/></span><strong>{isExtension?'Prepare an application':'Find your next chapter'}</strong><p>{isExtension?'Fill supported fields with a review before changes.':'Let ORVIA prepare a fellowship application, with you in control.'}</p><span className="featured-bottom">Explore the application demo <ArrowRight size={13}/></span></button></>:<><div className="goal-bubble"><span>YOUR GOAL</span><p>{goal||flowCopy[flow].goal}</p></div><div className="run-heading"><span className={'run-symbol '+phase}>{phase==='complete'?<Check size={20}/>:phase==='error'?<TriangleAlert size={20}/>:phase==='approval'?<ShieldCheck size={20}/>:active?<Loader2 size={20} className="spin"/>:<Pause size={20}/>}</span><div><span className="eyebrow">{phase==='complete'?'TASK COMPLETE':phase==='approval'?'YOU DECIDE':'ORVIA IS ON IT'}</span><h3>{phaseLabels[phase]}</h3></div></div><div className="progress-track"><div style={{width:progress+'%'}}/></div>
 <div className="task-list">{[{label:'Understand the page',done:progress>=40,active:progress<40},{label:'Keep private details local',done:progress>=60,active:progress>=40&&progress<60},{label:flow==='summary'?'Prepare a concise summary':flow==='extract'?'Organize the key details':'Prepare your application',done:progress>=80,active:progress>=60&&progress<80},{label:flow==='summary'||flow==='extract'?'Check the final result':'Review, act and verify',done:progress===100,active:progress>=80&&progress<100}].map((t,i)=><div key={t.label} className={t.done?'done':t.active?'current':''}><span>{t.done?<Check size={12}/>:i+1}</span>{t.label}{t.active&&active&&<span className="step-dot"/>}</div>)}</div>
 {phase==='approval'&&pending&&<div className="approval-card"><div className="approval-title"><Shield size={17}/><strong>{isExtension||flow==='form'?'Review before filling':'Ready for your go-ahead'}</strong></div><p>{isExtension?'Fill these values on the current page. The website can read them after filling. Submission stays manual.':flow==='application'?'Fill and simulate submitting this sample application. Nothing will be sent to a real organization.':'Fill these values in the sample form.'}</p><div className="approval-destination"><Globe size={12}/>{pending.origin}</div><dl>{pending.fields.map(key=><div key={key}><dt>{key}</dt><dd>{profile[key as keyof Profile]}</dd></div>)}</dl><button className="primary full" onClick={()=>void approve()}>{isExtension||flow==='form'?'Approve & fill fields':'Approve demo application'}<ArrowRight size={14}/></button><button className="text-button centered" onClick={cancel}>Decline and stop</button></div>}
 {phase==='complete'&&<div className="result-card"><span className="result-kicker"><CheckCircle2 size={14}/>{flow==='extract'?'Your extracted data':flow==='summary'?'Your page, at a glance':isExtension?'Ready for your review':'One step closer'}</span><p className="result-text">{result}</p>{flow==='extract'&&<dl>{Object.entries(data).filter(([k])=>k!=='excerpt'&&k!=='headings').map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>}{flow==='extract'&&<button className="secondary full" onClick={()=>saveFile('orvia-extracted-data.json',JSON.stringify(data,null,2))}><Download size={14}/>Export JSON</button>}<button className="receipt-link" onClick={()=>setDrawer('privacy')}><ShieldCheck size={15}/>View privacy receipt<ArrowUpRight size={13}/></button></div>}
 {phase==='error'&&<div className="error-card"><TriangleAlert size={18}/><strong>Stopped safely</strong><p>{error}</p><button className="secondary full" onClick={()=>void start(flow)}><RotateCcw size={14}/>Re-observe and try again</button></div>}
 {phase==='cancelled'&&<div className="result-card"><p>No further actions will run. You can start a fresh task whenever you’re ready.</p><button className="secondary full" onClick={reset}>Start a new task</button></div>}
 {active&&phase!=='approval'&&<div className="live-status"><span className="live-dot"/><span>{logs[logs.length-1]?.detail}</span></div>}
 <button className="activity-link" onClick={()=>setDrawer('activity')}><ActivityIcon size={14}/><span>View activity</span><span>{logs.length} events</span><ChevronRight size={14}/></button>
 </>}
 </div><div className="composer-area"><div className="composer"><textarea ref={input} aria-label="Your goal" value={goal} disabled={active} onChange={e=>{setGoal(e.target.value);const text=e.target.value.toLowerCase();setFlow(/summari/.test(text)?'summary':/extract|table|data/.test(text)?'extract':/fill/.test(text)?'form':'application');}} placeholder="What would you like to do?" rows={2} maxLength={1000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!active)void start(flow);}}}/><div className="composer-bottom"><span><LockKeyhole size={11}/> Private workspace</span>{active?<button className="stop-button" aria-label="Stop task" onClick={cancel}><Pause size={15}/></button>:<button className="send-button" aria-label="Run goal" onClick={()=>void start(flow)}><ArrowRight size={18}/></button>}</div></div><div className="composer-caption">{active?<span>{elapsed.toFixed(1)}s · {phase==='approval'?'Awaiting your approval':'Working locally'}</span>:<span>Local prototype · AI reasoning simulated</span>}<button onClick={()=>setDrawer('metrics')} aria-label="Open metrics"><ActivityIcon size={13}/></button></div></div>
 </aside></main>
 {!isExtension&&<footer className="page-footer"><span><ShieldCheck size={14}/> Your browser. Your data. Your call.</span><div><span>DOM-first perception</span><i/><span>Local privacy checks</span><i/><span>Human-controlled actions</span></div><span>ORVIA / 2026</span></footer>}
 {drawer&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setDrawer(null);}}><div className="drawer" ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="drawer-title"><header><div><span className="eyebrow">ORVIA · TRANSPARENCY</span><h2 id="drawer-title">{drawer==='activity'?'Every step, in the open.':drawer==='privacy'?'Your privacy receipt.':drawer==='metrics'?'Measure what matters.':'Your local profile.'}</h2></div><button className="icon-button" aria-label="Close details" onClick={()=>setDrawer(null)}><X size={20}/></button></header><div className="drawer-tabs">{(['activity','privacy','metrics','profile'] as const).map(d=><button key={d} className={drawer===d?'selected':''} onClick={()=>setDrawer(d)}>{d}</button>)}</div>
 {drawer==='activity'&&<><p className="drawer-intro">From intent to verified result. Browser and planner boundaries are visible at every step.</p><div className="pipeline">{stages.map((s,i)=><span key={s}>{s}{i<6&&<ChevronRight size={10}/>}</span>)}</div>{logs.length?<div className="timeline">{logs.map((l,i)=><div key={i}><span className="timeline-dot"><Check size={11}/></span><div><div className="log-heading"><strong>{l.stage}</strong><span>{l.boundary}</span><time>{l.time}</time></div><p>{l.detail}</p></div></div>)}</div>:<div className="empty-detail"><Layers size={32}/><h3>Your next task starts here.</h3><p>Run a workflow to see its observation, privacy checks, action plan and verification.</p></div>}<div className="boundary-note"><LockKeyhole size={16}/><p><strong>Local planner boundary</strong><br/>This prototype uses deterministic planning in your browser. No remote model, OCR engine or vision model is connected.</p></div></>}
 {drawer==='privacy'&&<><div className="privacy-hero"><span><ShieldCheck size={29}/></span><h3>{receipt?'Private context. Accounted for.':'Protection starts on your device.'}</h3><p>No page context is sent to an external AI service by this prototype.</p></div><div className="receipt-stats"><div><strong>{receipt?receipt.findings.reduce((n,f)=>n+f.count,0):'—'}</strong><span>patterns masked</span></div><div><strong>{receipt?.blocked??'—'}</strong><span>fields excluded</span></div><div><strong>0 B</strong><span>AI network egress</span></div></div>{receipt?<><div className="receipt-meta"><span>SESSION RECEIPT</span><code>{receipt.id.slice(0,8)}</code><time>{new Date(receipt.time).toLocaleTimeString()}</time></div><h4>What stayed protected</h4><div className="findings">{receipt.findings.length?receipt.findings.map(f=><div key={f.kind}><ShieldCheck size={15}/><span>{f.kind}<small>{f.count} match{f.count===1?'':'es'}</small></span><code>{f.token}</code><span className="pill open">MASKED</span></div>):<p>No supported sensitive text patterns detected.</p>}<div><LockKeyhole size={15}/><span>Sensitive fields<small>Values never read</small></span><span>{receipt.blocked} excluded</span></div></div><h4>Sanitized context at the mock boundary</h4><p className="small-muted">{receipt.bytes.toLocaleString()} bytes prepared locally · 0 bytes transmitted. This is a session audit record, not a cryptographic privacy guarantee.</p><pre className="payload">{receipt.payload}</pre><button className="secondary full" onClick={()=>saveFile('orvia-privacy-receipt.json',JSON.stringify(receipt,null,2))}><Download size={14}/>Download privacy receipt</button></>:<div className="empty-detail"><p>Complete a page observation to generate a receipt with detected patterns and the exact sanitized payload.</p></div>}<div className="boundary-note"><TriangleAlert size={17}/><p>Rules detect email, phone and credential-like text plus known profile values. They do not reliably detect all PII, faces, images or obfuscated secrets. Form filling shares approved values with the destination page.</p></div></>}
 {drawer==='metrics'&&<><p className="drawer-intro">Honest instrumentation, without invented benchmarks. Quality metrics require a labeled evaluation dataset.</p><div className="metrics-list">{[['Visual Context Accuracy','Not evaluated','Vision is simulated in this prototype.'],['PII Precision / Recall','Not evaluated','Requires labeled sensitive and non-sensitive examples.'],['Redaction Precision','Not evaluated','Regex coverage is not an accuracy benchmark.'],['Client Resource Usage','Not measured','No cross-browser memory or CPU profiler attached.'],['End-to-End Latency',receipt?.elapsed?`${receipt.elapsed.toFixed(1)} s`:'Awaiting completion','Measured wall time, including animation and human approval.'],['External AI transmission','0 bytes','No AI network client is included.']].map(([label,value,note])=><div key={label}><span>{label}</span><strong>{value}</strong><p>{note}</p></div>)}</div><div className="boundary-note"><ActivityIcon size={17}/><p>Latency is a local run measurement, not model or production performance. Hosting may have its own operational request logs.</p></div></>}
 {drawer==='profile'&&<><p className="drawer-intro">Sample values for the application workflow. Kept in memory for this session; never sent to the mock planner unmasked.</p><div className="profile-fields">{Object.entries(profile).map(([key,value])=><label key={key}>{key}<input value={value} disabled={active} maxLength={150} onChange={e=>setProfile(p=>({...p,[key]:e.target.value}))}/></label>)}</div><h4>Explore resilience</h4><label className="toggle-row"><span><strong>Page layout changes</strong><small>Simulate stale context and watch ORVIA replan.</small></span><input type="checkbox" checked={chaos} disabled={active} onChange={e=>setChaos(e.target.checked)}/></label><label className="toggle-row"><span><strong>Visual perception unavailable</strong><small>Continue using the DOM-based fallback.</small></span><input type="checkbox" checked={fallback} disabled={active} onChange={e=>setFallback(e.target.checked)}/></label><button className="secondary full" disabled={active} onClick={()=>{setProfile({...sampleProfile});setChaos(false);setFallback(false);}}>Restore sample settings</button><p className="small-muted">Close this panel to use your changes. Reloading clears the profile and session receipt.</p></>}
 </div></div>}
 </div>;
}

